<?php
add_action('wp_head','jt_schema');
function jt_schema(){
$schemas=[];
$schemas[]=[
'@context'=>'https://schema.org',
'@type'=>'WebSite',
'name'=>get_bloginfo('name'),
'url'=>home_url('/')
];
if(is_singular()){
$post=get_queried_object();
$schemas[]=[
'@context'=>'https://schema.org',
'@type'=>'Article',
'headline'=>get_the_title($post),
'datePublished'=>get_the_date('c',$post),
'dateModified'=>get_the_modified_date('c',$post),
'author'=>[
'@type'=>'Person',
'name'=>get_the_author_meta('display_name',$post->post_author)
],
'url'=>get_permalink($post)
];
$items=[];
$items[]=[
'@type'=>'ListItem',
'position'=>1,
'name'=>get_bloginfo('name'),
'item'=>home_url('/')
];
$ancestors=array_reverse(get_post_ancestors($post));
$position=2;
foreach($ancestors as $ancestor){
$items[]=[
'@type'=>'ListItem',
'position'=>$position++,
'name'=>get_the_title($ancestor),
'item'=>get_permalink($ancestor)
];
}
$items[]=[
'@type'=>'ListItem',
'position'=>$position,
'name'=>get_the_title($post),
'item'=>get_permalink($post)
];
$schemas[]=[
'@context'=>'https://schema.org',
'@type'=>'BreadcrumbList',
'itemListElement'=>$items
];
}else{
$items=[];
$items[]=[
'@type'=>'ListItem',
'position'=>1,
'name'=>get_bloginfo('name'),
'item'=>home_url('/')
];
$position=2;
if(is_archive()){
$object=get_queried_object();
if($object){
$name=$object->name??get_the_archive_title();
$link=is_post_type_archive()?get_post_type_archive_link($object->name):get_term_link($object);
if(is_wp_error($link)){$link=home_url('/');}
$items[]=[
'@type'=>'ListItem',
'position'=>$position,
'name'=>$name,
'item'=>$link
];
}
}
$schemas[]=[
'@context'=>'https://schema.org',
'@type'=>'BreadcrumbList',
'itemListElement'=>$items
];
}
foreach($schemas as $schema){
echo '<script type="application/ld+json">'.wp_json_encode($schema).'</script>';
}
}
